### ISSUE TITLE
Chapter 04 npm start fails

### ISSUE THREAD

**Issue by khtan** [PacktPublishing/Angular-Test-Driven-Development-Second-Edition#1]
When I run npm start on the code in Chappter 04, it fails.

Transcript:
npm start

> angular-TDD-chapter-4@1.0.0 start d:\users\khtan\projects\Angular2TDD2ed\Chapter 04
> tsc && concurrently "tsc -w" "lite-server" 

e2e/app.e2e-spec.ts(5,37): error TS2559: Type 'By' has no properties in common with type 'Locator'.
e2e/app.e2e-spec.ts(12,44): error TS2345: Argument of type '"Angular Protractor"' is not assignable to parameter of type 'Expected<Promise<string>>'.
e2e/app.e2e-spec.ts(16,44): error TS2345: Argument of type '3' is not assignable to parameter of type 'Expected<Promise<number>>'.
e2e/app.e2e-spec.ts(20,57): error TS2345: Argument of type '"test"' is not assignable to parameter of type 'Expected<Promise<string>>'.
e2e/app.e2e-spec.ts(24,56): error TS2345: Argument of type '"refactor"' is not assignable to parameter of type 'Expected<Promise<string>>'.
node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
...

**Comment by sarvesh-packt** [comment]
Please reopen if the issue still persists.
